package bhtweb.dbaccess;

import java.sql.Statement;
import java.security.KeyStore.PrivateKeyEntry;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.resource.spi.RetryableUnavailableException;

import bhtweb.entities.BHTPost;
import bhtweb.utils.DataTypeUtils;
import bhtweb.utils.DateTimeUtils;

public class PostMapper extends DBMapper {

	//Hằng số để ta chỉnh pageLimit mặc định khi fetchPost, searchPost,...
	//Đây là số element tối đa của một trang.
	private static final Integer DEFAULT_PAGE_LIMIT = 10;
	
	//Các chuỗi phục vụ cho preparedStatement.
	private static final String insertPostStr = "INSERT INTO POST VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	private static final String updatePostStr = "UPDATE POST SET PostTitle = ?, PostContentURL = ?, PostSubmitDtm = ?, PostPublishDtm = ?, PostReadTime = ?, NumVote = ?, NumView = ?, PostSoftDeleted = ?, PostHidden = ?, PostApproved = ?, PosterUserID = ?, PostCategoryID = ? WHERE PostID = ?";
	private static final String fetchPostStr = "SELECT * FROM POST LIMIT ?,? ORDER BY postPublishDtm DESC";
	
	//preparedStatement.
	
	public PostMapper() throws Exception {
		super();
		//Tạo preparedStatement.
	}
	
	public Boolean updatePost (BHTPost postDTO) {
		try (PreparedStatement updatePostPst = getConnection().prepareStatement(updatePostStr)){
			updatePostPst.setString(1, postDTO.getPostTitle());
			updatePostPst.setString(2, postDTO.getPostContentURL());
			updatePostPst.setTimestamp(3, DateTimeUtils.getTimestamptFromDate(postDTO.getPostPublishDtm()));
			updatePostPst.setLong(4, postDTO.getPostReadTime());
			updatePostPst.setLong(5, postDTO.getNumVote());
			updatePostPst.setLong(6, postDTO.getNumView());
			updatePostPst.setBoolean(7, postDTO.getPostSoftDeleted());
			updatePostPst.setBoolean(8, postDTO.getPostHidden());
			updatePostPst.setBoolean(9, postDTO.getPostApproved());
			updatePostPst.setLong(10, postDTO.getPosterUserID());
			updatePostPst.setLong(11, postDTO.getPostCategoryID());
			updatePostPst.setLong(12, postDTO.getPostID());
			
			//Chạy lệnh cập nhật post.
			Integer rows = updatePostPst.executeUpdate();
			if (rows > 0)
				return true;
			else
				return false;
		} catch (Exception ex) {
			// TODO: handle exception
			ex.printStackTrace();
		}
		return false;
	}
	
	public BHTPost insertPost (BHTPost postDTO) {
		try (PreparedStatement insertPostPst = getConnection().prepareStatement(insertPostStr, Statement.RETURN_GENERATED_KEYS)){
			//AutoGenerated ID, vì vậy lúc nào cũng truyền vào 0 cho ID khi tạo.
			insertPostPst.setLong(1, 0);
			insertPostPst.setString(2, postDTO.getPostTitle());
			insertPostPst.setString(3, postDTO.getPostContentURL());
			insertPostPst.setTimestamp(4, DateTimeUtils.getTimestamptFromDate(postDTO.getPostPublishDtm()));
			insertPostPst.setLong(5, postDTO.getPostReadTime());
			insertPostPst.setLong(6, postDTO.getNumVote());
			insertPostPst.setLong(7, postDTO.getNumView());
			insertPostPst.setBoolean(8, postDTO.getPostSoftDeleted());
			insertPostPst.setBoolean(9, postDTO.getPostHidden());
			insertPostPst.setBoolean(10, postDTO.getPostApproved());
			insertPostPst.setLong(11, postDTO.getPosterUserID());
			insertPostPst.setLong(12, postDTO.getPostCategoryID());
			
			//Chạy lệnh thêm mới một Post.
			insertPostPst.executeUpdate();
			
			//Lấy về ID vừa được tạo.
			ResultSet rSet = insertPostPst.getGeneratedKeys();
			rSet.next();
			postDTO.setPostID(rSet.getLong(1));
			
		}catch (Exception ex) {
			ex.printStackTrace();
			postDTO.setPostID(null);
		}
		return postDTO;
	}
	
	//Hàm fetch sẽ sử dụng pageLimit mặc định như đã được cấu hình ở trên.
	public ArrayList<BHTPost> fetchPost (Integer pageNo){
		return fetchPost(pageNo, DEFAULT_PAGE_LIMIT);
	}
	
	public ArrayList<BHTPost> fetchPost (Integer pageNo, Integer pageLimit){
		Integer startLimit = (pageNo - 1) * pageLimit;
		Integer offSet = pageLimit;
		
		ArrayList<BHTPost> postsResult = new ArrayList<>();
		
		try (PreparedStatement fetchPostPst = getConnection().prepareStatement(fetchPostStr)) {
			fetchPostPst.setLong(1, startLimit);
			fetchPostPst.setLong(2, offSet);
			
			ResultSet rSet = fetchPostPst.executeQuery();
			
			while (rSet != null && rSet.next()) {
				BHTPost postDTO = getPostDTOFromCurrentResultSet(rSet);
				
				postsResult.add(postDTO);
			}
			
		}catch (Exception ex) {
			// TODO: handle exception
			ex.printStackTrace();
			return null;
		}

		return postsResult;
	}
	
	public ArrayList<BHTPost> searchPost (BHTPost similarPost, Integer pageNo){
		return searchPost(similarPost, pageNo, DEFAULT_PAGE_LIMIT);
	}
	
	public ArrayList<BHTPost> searchPost (BHTPost similarPost, Integer pageNo, Integer pageLimit){
		
		ArrayList<BHTPost> searchPostResult = new ArrayList<>();
		
		String searchSQLStr = getSearchSQLFromDTO(similarPost);
		
		try (PreparedStatement searchPostPst = getConnection().prepareStatement(searchSQLStr)){
			ResultSet rSet = searchPostPst.executeQuery();
			
			while (rSet != null && rSet.next()) {
				BHTPost postDTO = getPostDTOFromCurrentResultSet(rSet);
				searchPostResult.add(postDTO);
			}
			
		}catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			return null;
		}
		return searchPostResult;
	}
	
	//Hàm lấy một DTO từ resultSet hiện tại.
	private BHTPost getPostDTOFromCurrentResultSet (ResultSet rSet) throws Exception {
		BHTPost postDTO = new BHTPost();
		try {
			postDTO.setNumView(rSet.getLong("NumView"));
			postDTO.setNumVote(rSet.getLong("NumVote"));
			postDTO.setPostApproved(rSet.getBoolean("PostApproved"));
			postDTO.setPostCategoryID(rSet.getLong("PostCategoryID"));
			postDTO.setPostContentURL(rSet.getString("PostContentURL"));
			postDTO.setPosterUserID(rSet.getLong("PosterUserID"));
			postDTO.setPostHidden(rSet.getBoolean("PostHidden"));
			postDTO.setPostID(rSet.getLong("PostID"));
			postDTO.setPostPublishDtm(rSet.getTimestamp("PostPublishDtm"));
			postDTO.setPostReadTime(rSet.getLong("PostReadTime"));
			postDTO.setPostSoftDeleted(rSet.getBoolean("PostSoftDeleted"));
			postDTO.setPostSubmitDtm(rSet.getTimestamp("PostSubmitDtm"));
			postDTO.setPostTitle(rSet.getString("PostTitle"));
			
		}catch (Exception e) {
			// TODO: handle exception
			throw e;
		}
		return postDTO;
	}
	
	//Hàm trả về câu truy vấn SQL (chuỗi) để tìm kiếm theo các trường thông tin khác null của DTO truyền vào.
	private String getSearchSQLFromDTO (BHTPost similarPost) {
		//Tạo statement SQL từ đối tượng DTO truyền vào.
		String searchSQLStr = "SELECT * FROM POST WHERE";
		if (similarPost.getPostApproved() != null)
			searchSQLStr += "PostApproved = " + DataTypeUtils.getStringFromBoolean(similarPost.getPostApproved()) + " AND";
		if (similarPost.getPostHidden() != null)
			searchSQLStr += "PostHidden = " + DataTypeUtils.getStringFromBoolean(similarPost.getPostHidden())  + " AND"; 
		if (similarPost.getPostSoftDeleted() != null)
			searchSQLStr += "PostSoftDeleted = " + DataTypeUtils.getStringFromBoolean(similarPost.getPostSoftDeleted()) + " AND";
		if (similarPost.getNumView() != null)
			searchSQLStr += "NumView = " + similarPost.getNumView().toString() + " AND";
		if (similarPost.getNumVote() != null)
			searchSQLStr += "NumVote = " + similarPost.getNumVote().toString() + " AND";
		if (similarPost.getPostCategoryID() != null)
			searchSQLStr += "PostCategoryID = " + similarPost.getPostCategoryID().toString() + " AND";
		if (similarPost.getPostContentURL() != null)
			searchSQLStr += "PostContentURL = " + similarPost.getPostContentURL() + " AND";
		if (similarPost.getPosterUserID() != null)
			searchSQLStr += "PosterUserID = " + similarPost.getPosterUserID().toString() + " AND";
		if (similarPost.getPostID() != null)
			searchSQLStr += "PostID = " + similarPost.getPostID().toString() + " AND";
		if (similarPost.getPostPublishDtm() != null)
			searchSQLStr += "PostPublishDtm = " + similarPost.getPostPublishDtm() + " AND"; 
		if (similarPost.getPostReadTime() != null)
			searchSQLStr += "PostReadTime = " + similarPost.getPostReadTime() + " AND";
		if (similarPost.getPostSubmitDtm() != null)
			searchSQLStr += "PostSubmitDtm = " + similarPost.getPostSubmitDtm() + " AND";
		if (similarPost.getPostTitle() != null)
			searchSQLStr += "PostTitle like \'%" + similarPost.getPostTitle() + "%\'" + " AND";
		//Cần thiết để câu lệnh SQL của chúng ta đúng cú pháp.
		searchSQLStr += "1=1";
		return searchSQLStr;
	}
}
